services:
  tg_bot_crawler:
    build: .
    command: python bot.py
    volumes:
      - ./:/app

  celery_worker:
    build: .
    command: celery -A tasks worker -B --loglevel=INFO -c 10
    volumes:
      - ./:/app

  redis:
    image: redis:latest

    expose:
      - "6379"